from django.conf.urls import patterns, url
from core import views

urlpatterns = patterns('',
    url(r'^candidates/$',
        views.candidates_view,
        name='candidates'
    ),
    url(r'^compare/$',
        views.compare_view,
        name='compare'
    ),
    url(r'^edit/(?P<unique_key>[^/]+)/$',
        views.edit_redirect_view,
        name='edit'
    ),
    url(r'^edit/(?P<unique_key>[^/].+)/profile/$',
        views.edit_profile_view,
        name='edit_profile'
    ),
    url(r'^edit/(?P<unique_key>[^/].+)/questions/$',
        views.edit_questions_view,
        name='edit_questions'
    ),
    url(r'^profile/(?P<politician_id>\d+)/$',
        views.profile_view,
        name='profile'
    ),
    url(r'^profile_info/(?P<politician_id>\d+)/$',
        views.profile_info_view,
        name='profile_info'
    ),
    url(r'^politician_answer/$',
        views.politician_answer_view,
        name='politician_answer'
    ),
    url(r'^publish/$',
        views.publish_view,
        name='publish'
    ),
    url(r'^unpublish/$',
        views.unpublish_view,
        name='unpublish'
    ),
    url(r'^link/add/$',
        views.add_link_view,
        name='add_link'
    ),
    url(r'^link/delete/$',
        views.delete_link_view,
        name='delete_link'
    ),
    url(r'^party/(?P<party_name>\w+)/login/$',
        views.party_login_view,
        name='party_login'
    ),
    url(r'^party/(?P<party_name>\w+)/logout/$',
        views.party_logout_view,
        name='party_logout'
    ),
    url(r'^party/(?P<party_name>\w+)/$',
        views.party_dashboard_view,
        name='party_dashboard'
    ),
    url(r'^party/(?P<party_name>\w+)/export/$',
        views.party_export_view,
        name='party_export'
    ),
    url(r'^party/(?P<party_name>\w+)/politician/add/$',
        views.party_politician_add_view,
        name='party_politician_add'
    ),
    url(r'^party/(?P<party_name>\w+)/politician/(?P<politician_id>\d+)/edit/$',
        views.party_politician_edit_view,
        name='party_politician_edit'
    ),
    url(
        r'^party/(?P<party_name>\w+)/politician/(?P<politician_id>\d+)/delete/$',
        views.party_politician_delete_view,
        name='party_politician_delete'
    ),
)
